// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: bodoke/v1/agent.proto

package bodokev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage is any message the agent can send to the manager.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_Status
	//	*AgentMessage_Heartbeat
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetStatus() *JobStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type AgentMessage_Status struct {
	Status *JobStatusUpdate `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Payload() {}

func (*AgentMessage_Status) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

// ManagerMessage is any message the manager can send to an agent.
type ManagerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ManagerMessage_Register
	//	*ManagerMessage_RunJob
	//	*ManagerMessage_CancelJob
	//	*ManagerMessage_Restore
	Payload       isManagerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerMessage) Reset() {
	*x = ManagerMessage{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerMessage) ProtoMessage() {}

func (x *ManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerMessage.ProtoReflect.Descriptor instead.
func (*ManagerMessage) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerMessage) GetPayload() isManagerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ManagerMessage) GetRegister() *RegisterResponse {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ManagerMessage) GetRunJob() *RunJobCommand {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_RunJob); ok {
			return x.RunJob
		}
	}
	return nil
}

func (x *ManagerMessage) GetCancelJob() *CancelJobCommand {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *ManagerMessage) GetRestore() *RunRestoreCommand {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

type isManagerMessage_Payload interface {
	isManagerMessage_Payload()
}

type ManagerMessage_Register struct {
	Register *RegisterResponse `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ManagerMessage_RunJob struct {
	RunJob *RunJobCommand `protobuf:"bytes,2,opt,name=run_job,json=runJob,proto3,oneof"`
}

type ManagerMessage_CancelJob struct {
	CancelJob *CancelJobCommand `protobuf:"bytes,3,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type ManagerMessage_Restore struct {
	Restore *RunRestoreCommand `protobuf:"bytes,4,opt,name=restore,proto3,oneof"`
}

func (*ManagerMessage_Register) isManagerMessage_Payload() {}

func (*ManagerMessage_RunJob) isManagerMessage_Payload() {}

func (*ManagerMessage_CancelJob) isManagerMessage_Payload() {}

func (*ManagerMessage_Restore) isManagerMessage_Payload() {}

// RegisterRequest is the first message an agent sends when it connects.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // UUID persisted by agent; empty on first boot
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                    // pre-shared token issued by manager UI
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // e.g. ["docker","postgres","mysql","mongodb"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // manager echoes back (or assigns) the UUID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RunJobCommand triggers a backup run on the agent.
type RunJobCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // unique per execution; used to correlate status updates
	Spec          *JobSpec               `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobCommand) Reset() {
	*x = RunJobCommand{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobCommand) ProtoMessage() {}

func (x *RunJobCommand) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobCommand.ProtoReflect.Descriptor instead.
func (*RunJobCommand) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RunJobCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunJobCommand) GetSpec() *JobSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// CancelJobCommand asks the agent to abort an in-progress run.
type CancelJobCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobCommand) Reset() {
	*x = CancelJobCommand{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobCommand) ProtoMessage() {}

func (x *CancelJobCommand) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobCommand.ProtoReflect.Descriptor instead.
func (*CancelJobCommand) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CancelJobCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// RunRestoreCommand asks the agent to restore a previous backup.
type RunRestoreCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`                   // the backup_run to restore
	ArchivePath   string                 `protobuf:"bytes,2,opt,name=archive_path,json=archivePath,proto3" json:"archive_path,omitempty"` // rclone remote path or local path
	TargetPath    string                 `protobuf:"bytes,3,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`    // where to restore on the agent's host
	Decrypt       bool                   `protobuf:"varint,4,opt,name=decrypt,proto3" json:"decrypt,omitempty"`
	EncryptKeyRef string                 `protobuf:"bytes,5,opt,name=encrypt_key_ref,json=encryptKeyRef,proto3" json:"encrypt_key_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRestoreCommand) Reset() {
	*x = RunRestoreCommand{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRestoreCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRestoreCommand) ProtoMessage() {}

func (x *RunRestoreCommand) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRestoreCommand.ProtoReflect.Descriptor instead.
func (*RunRestoreCommand) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RunRestoreCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunRestoreCommand) GetArchivePath() string {
	if x != nil {
		return x.ArchivePath
	}
	return ""
}

func (x *RunRestoreCommand) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *RunRestoreCommand) GetDecrypt() bool {
	if x != nil {
		return x.Decrypt
	}
	return false
}

func (x *RunRestoreCommand) GetEncryptKeyRef() string {
	if x != nil {
		return x.EncryptKeyRef
	}
	return ""
}

// JobStatusUpdate streams progress from agent to manager.
type JobStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        RunStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=bodoke.v1.RunStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,4,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`                          // SHA-256 of final archive; set on SUCCESS
	ArchivePath   string                 `protobuf:"bytes,6,opt,name=archive_path,json=archivePath,proto3" json:"archive_path,omitempty"` // final remote path; set on SUCCESS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusUpdate) Reset() {
	*x = JobStatusUpdate{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusUpdate) ProtoMessage() {}

func (x *JobStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusUpdate.ProtoReflect.Descriptor instead.
func (*JobStatusUpdate) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *JobStatusUpdate) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobStatusUpdate) GetStatus() RunStatus {
	if x != nil {
		return x.Status
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *JobStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobStatusUpdate) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *JobStatusUpdate) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *JobStatusUpdate) GetArchivePath() string {
	if x != nil {
		return x.ArchivePath
	}
	return ""
}

// HeartbeatRequest is sent periodically by the agent.
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActiveRuns    int32                  `protobuf:"varint,2,opt,name=active_runs,json=activeRuns,proto3" json:"active_runs,omitempty"`
	CpuPercentX10 int64                  `protobuf:"varint,3,opt,name=cpu_percent_x10,json=cpuPercentX10,proto3" json:"cpu_percent_x10,omitempty"` // CPU% * 10 to avoid float
	MemMb         int64                  `protobuf:"varint,4,opt,name=mem_mb,json=memMb,proto3" json:"mem_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_bodoke_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveRuns() int32 {
	if x != nil {
		return x.ActiveRuns
	}
	return 0
}

func (x *HeartbeatRequest) GetCpuPercentX10() int64 {
	if x != nil {
		return x.CpuPercentX10
	}
	return 0
}

func (x *HeartbeatRequest) GetMemMb() int64 {
	if x != nil {
		return x.MemMb
	}
	return 0
}

var File_bodoke_v1_agent_proto protoreflect.FileDescriptor

const file_bodoke_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x15bodoke/v1/agent.proto\x12\tbodoke.v1\x1a\x15bodoke/v1/types.proto\"\xc6\x01\n" +
	"\fAgentMessage\x128\n" +
	"\bregister\x18\x01 \x01(\v2\x1a.bodoke.v1.RegisterRequestH\x00R\bregister\x124\n" +
	"\x06status\x18\x02 \x01(\v2\x1a.bodoke.v1.JobStatusUpdateH\x00R\x06status\x12;\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1b.bodoke.v1.HeartbeatRequestH\x00R\theartbeatB\t\n" +
	"\apayload\"\x83\x02\n" +
	"\x0eManagerMessage\x129\n" +
	"\bregister\x18\x01 \x01(\v2\x1b.bodoke.v1.RegisterResponseH\x00R\bregister\x123\n" +
	"\arun_job\x18\x02 \x01(\v2\x18.bodoke.v1.RunJobCommandH\x00R\x06runJob\x12<\n" +
	"\n" +
	"cancel_job\x18\x03 \x01(\v2\x1b.bodoke.v1.CancelJobCommandH\x00R\tcancelJob\x128\n" +
	"\arestore\x18\x04 \x01(\v2\x1c.bodoke.v1.RunRestoreCommandH\x00R\arestoreB\t\n" +
	"\apayload\"\x9c\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"c\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"N\n" +
	"\rRunJobCommand\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12&\n" +
	"\x04spec\x18\x02 \x01(\v2\x12.bodoke.v1.JobSpecR\x04spec\")\n" +
	"\x10CancelJobCommand\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xb0\x01\n" +
	"\x11RunRestoreCommand\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12!\n" +
	"\farchive_path\x18\x02 \x01(\tR\varchivePath\x12\x1f\n" +
	"\vtarget_path\x18\x03 \x01(\tR\n" +
	"targetPath\x12\x18\n" +
	"\adecrypt\x18\x04 \x01(\bR\adecrypt\x12&\n" +
	"\x0fencrypt_key_ref\x18\x05 \x01(\tR\rencryptKeyRef\"\xd4\x01\n" +
	"\x0fJobStatusUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.bodoke.v1.RunStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rbytes_written\x18\x04 \x01(\x03R\fbytesWritten\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12!\n" +
	"\farchive_path\x18\x06 \x01(\tR\varchivePath\"\x8d\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vactive_runs\x18\x02 \x01(\x05R\n" +
	"activeRuns\x12&\n" +
	"\x0fcpu_percent_x10\x18\x03 \x01(\x03R\rcpuPercentX10\x12\x15\n" +
	"\x06mem_mb\x18\x04 \x01(\x03R\x05memMb2Q\n" +
	"\fAgentService\x12A\n" +
	"\aConnect\x12\x17.bodoke.v1.AgentMessage\x1a\x19.bodoke.v1.ManagerMessage(\x010\x01B4Z2github.com/Selknam-Tech/BodokeBackupProto/bodokev1b\x06proto3"

var (
	file_bodoke_v1_agent_proto_rawDescOnce sync.Once
	file_bodoke_v1_agent_proto_rawDescData []byte
)

func file_bodoke_v1_agent_proto_rawDescGZIP() []byte {
	file_bodoke_v1_agent_proto_rawDescOnce.Do(func() {
		file_bodoke_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bodoke_v1_agent_proto_rawDesc), len(file_bodoke_v1_agent_proto_rawDesc)))
	})
	return file_bodoke_v1_agent_proto_rawDescData
}

var file_bodoke_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bodoke_v1_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),      // 0: bodoke.v1.AgentMessage
	(*ManagerMessage)(nil),    // 1: bodoke.v1.ManagerMessage
	(*RegisterRequest)(nil),   // 2: bodoke.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 3: bodoke.v1.RegisterResponse
	(*RunJobCommand)(nil),     // 4: bodoke.v1.RunJobCommand
	(*CancelJobCommand)(nil),  // 5: bodoke.v1.CancelJobCommand
	(*RunRestoreCommand)(nil), // 6: bodoke.v1.RunRestoreCommand
	(*JobStatusUpdate)(nil),   // 7: bodoke.v1.JobStatusUpdate
	(*HeartbeatRequest)(nil),  // 8: bodoke.v1.HeartbeatRequest
	(*JobSpec)(nil),           // 9: bodoke.v1.JobSpec
	(RunStatus)(0),            // 10: bodoke.v1.RunStatus
}
var file_bodoke_v1_agent_proto_depIdxs = []int32{
	2,  // 0: bodoke.v1.AgentMessage.register:type_name -> bodoke.v1.RegisterRequest
	7,  // 1: bodoke.v1.AgentMessage.status:type_name -> bodoke.v1.JobStatusUpdate
	8,  // 2: bodoke.v1.AgentMessage.heartbeat:type_name -> bodoke.v1.HeartbeatRequest
	3,  // 3: bodoke.v1.ManagerMessage.register:type_name -> bodoke.v1.RegisterResponse
	4,  // 4: bodoke.v1.ManagerMessage.run_job:type_name -> bodoke.v1.RunJobCommand
	5,  // 5: bodoke.v1.ManagerMessage.cancel_job:type_name -> bodoke.v1.CancelJobCommand
	6,  // 6: bodoke.v1.ManagerMessage.restore:type_name -> bodoke.v1.RunRestoreCommand
	9,  // 7: bodoke.v1.RunJobCommand.spec:type_name -> bodoke.v1.JobSpec
	10, // 8: bodoke.v1.JobStatusUpdate.status:type_name -> bodoke.v1.RunStatus
	0,  // 9: bodoke.v1.AgentService.Connect:input_type -> bodoke.v1.AgentMessage
	1,  // 10: bodoke.v1.AgentService.Connect:output_type -> bodoke.v1.ManagerMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_bodoke_v1_agent_proto_init() }
func file_bodoke_v1_agent_proto_init() {
	if File_bodoke_v1_agent_proto != nil {
		return
	}
	file_bodoke_v1_types_proto_init()
	file_bodoke_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_Status)(nil),
		(*AgentMessage_Heartbeat)(nil),
	}
	file_bodoke_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagerMessage_Register)(nil),
		(*ManagerMessage_RunJob)(nil),
		(*ManagerMessage_CancelJob)(nil),
		(*ManagerMessage_Restore)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bodoke_v1_agent_proto_rawDesc), len(file_bodoke_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bodoke_v1_agent_proto_goTypes,
		DependencyIndexes: file_bodoke_v1_agent_proto_depIdxs,
		MessageInfos:      file_bodoke_v1_agent_proto_msgTypes,
	}.Build()
	File_bodoke_v1_agent_proto = out.File
	file_bodoke_v1_agent_proto_goTypes = nil
	file_bodoke_v1_agent_proto_depIdxs = nil
}
