// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: bodoke/v1/types.proto

package bodokev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SourceType identifies what kind of data a backup job targets.
type SourceType int32

const (
	SourceType_SOURCE_TYPE_UNSPECIFIED SourceType = 0
	SourceType_SOURCE_TYPE_DIRECTORY   SourceType = 1
	SourceType_SOURCE_TYPE_DOCKER      SourceType = 2
	SourceType_SOURCE_TYPE_DATABASE    SourceType = 3
	SourceType_SOURCE_TYPE_CONFIGFILES SourceType = 4
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNSPECIFIED",
		1: "SOURCE_TYPE_DIRECTORY",
		2: "SOURCE_TYPE_DOCKER",
		3: "SOURCE_TYPE_DATABASE",
		4: "SOURCE_TYPE_CONFIGFILES",
	}
	SourceType_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED": 0,
		"SOURCE_TYPE_DIRECTORY":   1,
		"SOURCE_TYPE_DOCKER":      2,
		"SOURCE_TYPE_DATABASE":    3,
		"SOURCE_TYPE_CONFIGFILES": 4,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_bodoke_v1_types_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_bodoke_v1_types_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_bodoke_v1_types_proto_rawDescGZIP(), []int{0}
}

// DestType identifies the backup destination backend.
type DestType int32

const (
	DestType_DEST_TYPE_UNSPECIFIED DestType = 0
	DestType_DEST_TYPE_RCLONE      DestType = 1
	DestType_DEST_TYPE_LOCAL       DestType = 2
)

// Enum value maps for DestType.
var (
	DestType_name = map[int32]string{
		0: "DEST_TYPE_UNSPECIFIED",
		1: "DEST_TYPE_RCLONE",
		2: "DEST_TYPE_LOCAL",
	}
	DestType_value = map[string]int32{
		"DEST_TYPE_UNSPECIFIED": 0,
		"DEST_TYPE_RCLONE":      1,
		"DEST_TYPE_LOCAL":       2,
	}
)

func (x DestType) Enum() *DestType {
	p := new(DestType)
	*p = x
	return p
}

func (x DestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DestType) Descriptor() protoreflect.EnumDescriptor {
	return file_bodoke_v1_types_proto_enumTypes[1].Descriptor()
}

func (DestType) Type() protoreflect.EnumType {
	return &file_bodoke_v1_types_proto_enumTypes[1]
}

func (x DestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DestType.Descriptor instead.
func (DestType) EnumDescriptor() ([]byte, []int) {
	return file_bodoke_v1_types_proto_rawDescGZIP(), []int{1}
}

// Compression algorithm for archives.
type Compression int32

const (
	Compression_COMPRESSION_UNSPECIFIED Compression = 0
	Compression_COMPRESSION_NONE        Compression = 1
	Compression_COMPRESSION_GZIP        Compression = 2
	Compression_COMPRESSION_ZSTD        Compression = 3
)

// Enum value maps for Compression.
var (
	Compression_name = map[int32]string{
		0: "COMPRESSION_UNSPECIFIED",
		1: "COMPRESSION_NONE",
		2: "COMPRESSION_GZIP",
		3: "COMPRESSION_ZSTD",
	}
	Compression_value = map[string]int32{
		"COMPRESSION_UNSPECIFIED": 0,
		"COMPRESSION_NONE":        1,
		"COMPRESSION_GZIP":        2,
		"COMPRESSION_ZSTD":        3,
	}
)

func (x Compression) Enum() *Compression {
	p := new(Compression)
	*p = x
	return p
}

func (x Compression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compression) Descriptor() protoreflect.EnumDescriptor {
	return file_bodoke_v1_types_proto_enumTypes[2].Descriptor()
}

func (Compression) Type() protoreflect.EnumType {
	return &file_bodoke_v1_types_proto_enumTypes[2]
}

func (x Compression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compression.Descriptor instead.
func (Compression) EnumDescriptor() ([]byte, []int) {
	return file_bodoke_v1_types_proto_rawDescGZIP(), []int{2}
}

// RunStatus represents the lifecycle state of a backup run.
type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNSPECIFIED RunStatus = 0
	RunStatus_RUN_STATUS_RUNNING     RunStatus = 1
	RunStatus_RUN_STATUS_SUCCESS     RunStatus = 2
	RunStatus_RUN_STATUS_FAILED      RunStatus = 3
	RunStatus_RUN_STATUS_CANCELLED   RunStatus = 4
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNSPECIFIED",
		1: "RUN_STATUS_RUNNING",
		2: "RUN_STATUS_SUCCESS",
		3: "RUN_STATUS_FAILED",
		4: "RUN_STATUS_CANCELLED",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNSPECIFIED": 0,
		"RUN_STATUS_RUNNING":     1,
		"RUN_STATUS_SUCCESS":     2,
		"RUN_STATUS_FAILED":      3,
		"RUN_STATUS_CANCELLED":   4,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bodoke_v1_types_proto_enumTypes[3].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_bodoke_v1_types_proto_enumTypes[3]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_bodoke_v1_types_proto_rawDescGZIP(), []int{3}
}

// JobSpec is sent inline from manager to agent; agents do not store jobs locally.
type JobSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName         string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	SourceType      SourceType             `protobuf:"varint,3,opt,name=source_type,json=sourceType,proto3,enum=bodoke.v1.SourceType" json:"source_type,omitempty"`
	SourceConfig    string                 `protobuf:"bytes,4,opt,name=source_config,json=sourceConfig,proto3" json:"source_config,omitempty"` // JSON blob
	DestType        DestType               `protobuf:"varint,5,opt,name=dest_type,json=destType,proto3,enum=bodoke.v1.DestType" json:"dest_type,omitempty"`
	DestConfig      string                 `protobuf:"bytes,6,opt,name=dest_config,json=destConfig,proto3" json:"dest_config,omitempty"` // JSON blob
	Compression     Compression            `protobuf:"varint,7,opt,name=compression,proto3,enum=bodoke.v1.Compression" json:"compression,omitempty"`
	Encryption      bool                   `protobuf:"varint,8,opt,name=encryption,proto3" json:"encryption,omitempty"`
	EncryptKeyRef   string                 `protobuf:"bytes,9,opt,name=encrypt_key_ref,json=encryptKeyRef,proto3" json:"encrypt_key_ref,omitempty"` // env:VAR_NAME or file:/path
	PreHook         string                 `protobuf:"bytes,10,opt,name=pre_hook,json=preHook,proto3" json:"pre_hook,omitempty"`                    // shell command, empty = none
	PostHook        string                 `protobuf:"bytes,11,opt,name=post_hook,json=postHook,proto3" json:"post_hook,omitempty"`
	RetentionConfig string                 `protobuf:"bytes,12,opt,name=retention_config,json=retentionConfig,proto3" json:"retention_config,omitempty"` // JSON: {"daily":7,"weekly":4,"monthly":12}
	// host_root_prefix is prepended to source paths when agent runs in a container
	HostRootPrefix string `protobuf:"bytes,13,opt,name=host_root_prefix,json=hostRootPrefix,proto3" json:"host_root_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_bodoke_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_bodoke_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_bodoke_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *JobSpec) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSpec) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobSpec) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *JobSpec) GetSourceConfig() string {
	if x != nil {
		return x.SourceConfig
	}
	return ""
}

func (x *JobSpec) GetDestType() DestType {
	if x != nil {
		return x.DestType
	}
	return DestType_DEST_TYPE_UNSPECIFIED
}

func (x *JobSpec) GetDestConfig() string {
	if x != nil {
		return x.DestConfig
	}
	return ""
}

func (x *JobSpec) GetCompression() Compression {
	if x != nil {
		return x.Compression
	}
	return Compression_COMPRESSION_UNSPECIFIED
}

func (x *JobSpec) GetEncryption() bool {
	if x != nil {
		return x.Encryption
	}
	return false
}

func (x *JobSpec) GetEncryptKeyRef() string {
	if x != nil {
		return x.EncryptKeyRef
	}
	return ""
}

func (x *JobSpec) GetPreHook() string {
	if x != nil {
		return x.PreHook
	}
	return ""
}

func (x *JobSpec) GetPostHook() string {
	if x != nil {
		return x.PostHook
	}
	return ""
}

func (x *JobSpec) GetRetentionConfig() string {
	if x != nil {
		return x.RetentionConfig
	}
	return ""
}

func (x *JobSpec) GetHostRootPrefix() string {
	if x != nil {
		return x.HostRootPrefix
	}
	return ""
}

var File_bodoke_v1_types_proto protoreflect.FileDescriptor

const file_bodoke_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15bodoke/v1/types.proto\x12\tbodoke.v1\"\xfa\x03\n" +
	"\aJobSpec\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x126\n" +
	"\vsource_type\x18\x03 \x01(\x0e2\x15.bodoke.v1.SourceTypeR\n" +
	"sourceType\x12#\n" +
	"\rsource_config\x18\x04 \x01(\tR\fsourceConfig\x120\n" +
	"\tdest_type\x18\x05 \x01(\x0e2\x13.bodoke.v1.DestTypeR\bdestType\x12\x1f\n" +
	"\vdest_config\x18\x06 \x01(\tR\n" +
	"destConfig\x128\n" +
	"\vcompression\x18\a \x01(\x0e2\x16.bodoke.v1.CompressionR\vcompression\x12\x1e\n" +
	"\n" +
	"encryption\x18\b \x01(\bR\n" +
	"encryption\x12&\n" +
	"\x0fencrypt_key_ref\x18\t \x01(\tR\rencryptKeyRef\x12\x19\n" +
	"\bpre_hook\x18\n" +
	" \x01(\tR\apreHook\x12\x1b\n" +
	"\tpost_hook\x18\v \x01(\tR\bpostHook\x12)\n" +
	"\x10retention_config\x18\f \x01(\tR\x0fretentionConfig\x12(\n" +
	"\x10host_root_prefix\x18\r \x01(\tR\x0ehostRootPrefix*\x93\x01\n" +
	"\n" +
	"SourceType\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SOURCE_TYPE_DIRECTORY\x10\x01\x12\x16\n" +
	"\x12SOURCE_TYPE_DOCKER\x10\x02\x12\x18\n" +
	"\x14SOURCE_TYPE_DATABASE\x10\x03\x12\x1b\n" +
	"\x17SOURCE_TYPE_CONFIGFILES\x10\x04*P\n" +
	"\bDestType\x12\x19\n" +
	"\x15DEST_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DEST_TYPE_RCLONE\x10\x01\x12\x13\n" +
	"\x0fDEST_TYPE_LOCAL\x10\x02*l\n" +
	"\vCompression\x12\x1b\n" +
	"\x17COMPRESSION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COMPRESSION_NONE\x10\x01\x12\x14\n" +
	"\x10COMPRESSION_GZIP\x10\x02\x12\x14\n" +
	"\x10COMPRESSION_ZSTD\x10\x03*\x88\x01\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x16RUN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RUN_STATUS_RUNNING\x10\x01\x12\x16\n" +
	"\x12RUN_STATUS_SUCCESS\x10\x02\x12\x15\n" +
	"\x11RUN_STATUS_FAILED\x10\x03\x12\x18\n" +
	"\x14RUN_STATUS_CANCELLED\x10\x04B4Z2github.com/Selknam-Tech/BodokeBackupProto/bodokev1b\x06proto3"

var (
	file_bodoke_v1_types_proto_rawDescOnce sync.Once
	file_bodoke_v1_types_proto_rawDescData []byte
)

func file_bodoke_v1_types_proto_rawDescGZIP() []byte {
	file_bodoke_v1_types_proto_rawDescOnce.Do(func() {
		file_bodoke_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bodoke_v1_types_proto_rawDesc), len(file_bodoke_v1_types_proto_rawDesc)))
	})
	return file_bodoke_v1_types_proto_rawDescData
}

var file_bodoke_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_bodoke_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bodoke_v1_types_proto_goTypes = []any{
	(SourceType)(0),  // 0: bodoke.v1.SourceType
	(DestType)(0),    // 1: bodoke.v1.DestType
	(Compression)(0), // 2: bodoke.v1.Compression
	(RunStatus)(0),   // 3: bodoke.v1.RunStatus
	(*JobSpec)(nil),  // 4: bodoke.v1.JobSpec
}
var file_bodoke_v1_types_proto_depIdxs = []int32{
	0, // 0: bodoke.v1.JobSpec.source_type:type_name -> bodoke.v1.SourceType
	1, // 1: bodoke.v1.JobSpec.dest_type:type_name -> bodoke.v1.DestType
	2, // 2: bodoke.v1.JobSpec.compression:type_name -> bodoke.v1.Compression
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bodoke_v1_types_proto_init() }
func file_bodoke_v1_types_proto_init() {
	if File_bodoke_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bodoke_v1_types_proto_rawDesc), len(file_bodoke_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bodoke_v1_types_proto_goTypes,
		DependencyIndexes: file_bodoke_v1_types_proto_depIdxs,
		EnumInfos:         file_bodoke_v1_types_proto_enumTypes,
		MessageInfos:      file_bodoke_v1_types_proto_msgTypes,
	}.Build()
	File_bodoke_v1_types_proto = out.File
	file_bodoke_v1_types_proto_goTypes = nil
	file_bodoke_v1_types_proto_depIdxs = nil
}
